//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Tasks_Manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Task_ManagerEntities : DbContext
    {
        public db_Task_ManagerEntities()
            : base("name=db_Task_ManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admins> tbl_admins { get; set; }
        public virtual DbSet<tbl_employeis> tbl_employeis { get; set; }
        public virtual DbSet<tbl_managers> tbl_managers { get; set; }
        public virtual DbSet<tbl_tasks> tbl_tasks { get; set; }
    }
}
