//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Tasks_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tasks
    {
        public long id { get; set; }
        public long eid { get; set; }
        public long mid { get; set; }
        public string manager { get; set; }
        public string employeef_name { get; set; }
        public string employeel_name { get; set; }
        public string title { get; set; }
        public string progress { get; set; }
        public string m_status { get; set; }
        public string e_status { get; set; }
        public string explanation { get; set; }
    }
}
